### ISSUE TITLE
Add docker compose

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/deepstack-ui#12]
To bring up deepstack and the UI

**Comment by salleq** [comment]
#14 
Might need some changes (mainly for volumes).
You've used "localstorage" in the example - it won't work unless "localstorage" is defined in docker-compose. That's why I'd prefer an example with just example path.

**Comment by robmarkcole** [comment]
Added in readme. @salleq can you give it a try?

**Comment by salleq** [comment]
@robmarkcole ah I meant that I removed "localstorage" from the pull request and typed a path in the docker host instead because that's usually safer. I've not added declaration for the volume "localstorage" in the docker-compose you have in your oneliner.

Sorry if I'm being confusing...

But, instead of adding the volume declaration I would change this:
`-v localstorage:/datastore \`
to this
`-v /path/to/config:/datastore`

**Comment by robmarkcole** [comment]
done
